/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectoalgcalc;

/**
 *
 * @author Sayuri
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
                String description = "<html><body>"
                + "<p style='font-size:16px;'><b>El proyecto consiste en desarrollar una Herramienta Interactiva para el Análisis Básico del Cálculo Integral,</b></p>"
                + "<p style='font-size:16px;'>con especial énfasis en un Solucionador Interactivo de Integrales Algebraicas.</p>"
                + "<p style='font-size:16px;'>El propósito es mejorar la comprensión y fomentar el aprendizaje autónomo de los estudiantes en el campo del cálculo integral.</p>"
                + "</body></html>";
        initComponents();
        Description.setText(description);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("BIENVENIDO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 580, -1));

        Description.setForeground(new java.awt.Color(51, 51, 51));
        Description.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 580, 250));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
